config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do


    devise_for :users
    root "fanfics#index", as: 'home'

    get 'about' => 'pages#about'

    # post 'chapter/create' =>
    resources :fanfics do
      resources :chapters do
        post 'create' => 'chapters#create'
      end
      resources :comments
    end
    resources :avatars, only: [:create, :destroy]
    resources :tags, only: [:show]
    resources :genres

  end
  # namespace :admin do
  #   resources :genres
  # end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :fanfic
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :fanfic
end

app/models/fanfic.rb
class Fanfic < ApplicationRecord
  # has_attached_file :image, styles: { }
  # do_not_validate_attachment_file_type :image
  # mount_uploader :avatar, AvatarUploader
  belongs_to :user, class_name: 'User', foreign_key: 'user_id', :optional => true
  has_many :comments
  has_many :chapters
  has_many :taggings
  has_many :tags, through: :taggings
  belongs_to :genre

  validates :title, :body, presence: true, length: {minimum: 2}

  def all_tags
    self.tags.map(&:name).join(', ')
  end

  def all_tags=(names)
    self.tags = names.split(',').map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :fanfics
  validates :name, presence: true, length: {minimum: 2}
  has_ancestry
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :fanfics, through: :taggings

  def self.counts
    self.select("name, count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id")
  end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :fanfic
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  has_many :fanfics, dependent: :destroy
  has_many :comments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable

  # attr_accessible  :username, :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  private
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end

end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :find_fanfic, only:[:destroy,:create,:update, :new, :show]
  before_action :find_chapter, only:[:destroy,:update]

  def new
    @chapter = Chapter.new
  end
  def create
    @chapter = @fanfic.chapters.create(chapter_params)
    if @chapter.save
      redirect_to @fanfic
    else
      render 'new'
    end
  end
  def show
    @chapter= @fanfic.chapters.find(params[:id])
  end
  def destroy
    # @chapter = @fanfic.chapters.find(params[:id])
    @chapter.destroy
    redirect_to fanfic_path(@fanfic)
  end
  def edit
    @fanfic= Fanfic.find(params[:fanfic_id])
    @chapter = @fanfic.chapters.find(params[:id])
  end
  def update
    @chapter = @fanfic.chapters.find(params[:id])
    @chapter.update_attributes(chapter_params)
    if @chapter.save
      redirect_to @fanfic
    else
      render 'edit'
    end
  end
  private
  def find_fanfic
    @fanfic = Fanfic.find(params[:fanfic_id])
  end
  def find_chapter
    @chapter = @fanfic.chapters.find(params[:id])
  end
  def chapter_params
    params.require(:chapter).permit(:body, :index, :title)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @fanfic = Fanfic.find(params[:fanfic_id])
    @comment = @fanfic.comments.create(comment_params)
    redirect_to fanfic_path(@fanfic)
  end

  private def comment_params
    params.require(:comment).permit(:username, :body)
  end
end

app/controllers/fanfics_controller.rb
class FanficsController < ApplicationController
  # http_basic_authenticate_with name: "admin", password: "1q2", except: [:index, :show]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_fanfic, only: [:show, :edit, :update, :destroy]

  # GET /fanfics
  # GET /fanfics.json
  def index
    @fanfics = Fanfic.paginate(page: params[:page], per_page: 10)
  end

  # GET /fanfics/1
  # GET /fanfics/1.json
  def show
    @chapters = @fanfic.chapters
  end

  # GET /fanfics/new
  def new
    @fanfic = Fanfic.new
  end

  # GET /fanfics/1/edit
  def edit
  end

  # POST /fanfics
  # POST /fanfics.json
  def create
    @fanfic = Fanfic.new(fanfic_params)

    if @fanfic.save
      redirect_to @fanfic, notice: 'Fanfic was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /fanfics/1
  # PATCH/PUT /fanfics/1.json
  def update
    if @fanfic.update(fanfic_params)
      redirect_to @fanfic, notice: 'Fanfic was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /fanfics/1
  # DELETE /fanfics/1.json
  def destroy
    @fanfic.destroy
    redirect_to fanfics_path, notice: 'Fanfic was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fanfic
      @fanfic = Fanfic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fanfic_params
      params.require(:fanfic).permit(:title, :body, :avatar, :all_tags, :genre_id)
    end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_genre, only: [:show, :edit, :destroy, :update]

  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.all
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
    @fanfics = Fanfic.where(genre_id: [@genre.subtree_ids]).paginate(page: params[:page], per_page: 10)
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to genres_path, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to genres_path, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_path, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_genre
    @genre = Genre.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def genre_params
    params.require(:genre).permit(:name, :parent_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about

  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find_by(name: params[:id])
    @fanfics = @tag.fanfics
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/fanfics_helper.rb
module FanficsHelper
  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size-1)
      yield(tag, classes[index.round])
    end
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/chapters/_form.html.erb
<%= form_for [@fanfic, @chapter], local: true  do |form| %>
  <%# if @fanfic.chapters.errors.any? %>
<!--    <div id="error_explanation">-->
<!--      <h2><%#= pluralize(@fanfic.chapters.errors.count, "error") %> prohibited this chapter from being saved:</h2>-->

<!--      <ul>-->
        <%# @fanfic.chapters.errors.full_messages.each do |message| %>
<!--          <li><%#= message %></li>-->
        <%# end %>
<!--      </ul>-->
<!--    </div>-->
  <%# end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field(:title, {:class => 'form-control'}) %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area(:body, {:class => 'form-control'}) %>
  </div>

  <div class="actions">
    <%= form.submit({:class => 'btn btn-success'}) %>
  </div>
<% end %>

app/views/chapters/_index.html.erb
<!--<p id="notice"><%#= notice %></p>-->

<h2>Chapters</h2>

<section id="chapters">
  <p id="notice"><%= notice %></p>
  <h2>
    <strong>Fanfic:</strong>
    <%#= @fanfic.chapter.fanfic_id %>
  </h2>
  <% @fanfic.chapters.each_with_index do |chapter,index| %>
    <div align="center">
      <h3>Chapter <%= index+1 %></h3>
    </div>
    <p>
      <strong>Title:</strong>
      <%= chapter.title %>
    </p>

    <p>
      <strong>Body:</strong>
      <%= chapter.body %>
    </p>


          <%= link_to 'Edit', edit_fanfic_chapter_path(@fanfic,chapter), class: 'btn btn-outline-primary btn-sm' %>
          <%= link_to 'Destroy', [chapter.fanfic,chapter], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger btn-sm' %>
  <%end %>
</section>
<br>
<%= link_to 'Edit', edit_fanfic_chapter_path(@fanfic) %> |
<%= link_to 'Back', fanfic_path %>

app/views/chapters/edit.html.erb
<h1>Editing Chapter</h1>

<%= render 'form', chapter: @chapter %>


<%= link_to 'Back', fanfic_chapters_path %>

app/views/chapters/new.html.erb
<h1>New Chapter</h1>

<%= render 'form', chapter: @chapter %>

<%= link_to 'Back', fanfics_path(@fanfic) %>

app/views/fanfics/_fanfic.html.erb
<h2><%= link_to fanfic.title, fanfic_path(fanfic) %></h2>
<section>
  <% if fanfic.genre.present? %>
    <%= link_to fanfic.genre.name, fanfic.genre %> |
  <%end %>
  <%= raw fanfic.tags.map(&:name).map{ |t| link_to t, tag_path(t), class: 'tag tag-primary'}.join(' ') %>
</section>
<!--<td><%#= fanfic.body %></td>-->


<%# @fanfics.each do |fanfic| %>
<!--  <tr>-->
<!--    <td><%#= link_to fanfic.title, fanfic_path(fanfic) %></td>-->
<!--    <td><%#= fanfic.body %></td>-->
<!--         <td><%##= link_to 'Show', fanfic %></td>-->
<!--         <td><%##= link_to 'Edit', edit_fanfic_path(fanfic) %></td>-->
<!--          <td><%##= link_to 'Destroy', fanfic, method: :delete, data: {confirm: 'Are you sure?'} %></td>-->
<!--  </tr>-->
<%# end %>

app/views/fanfics/_form.html.erb
<%= form_with(model: fanfic, local: true, html: {multipart: true}) do |form| %>
  <% if fanfic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fanfic.errors.count, "error") %> prohibited this fanfic from being saved:</h2>

      <ul>
        <% fanfic.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h4> <%= form.label :title %> </h4>
    <%= form.text_field(:title, {:class => 'form-control'}) %>
  </div>

  <div class="field">
    <h4> <%= form.label :body %> </h4>
    <%= form.trix_editor(:body, {:class => 'form-control'}) %>
  </div>

<!--  <div class="field">-->
    <%#= form.file_field :avatar %>
<!--  </div>-->

  <div class="field">
    <h4> <%= form.label :all_tags %> </h4>
    <%= form.text_field(:all_tags, {:class => 'form-control'}) %>
  </div>

  <div class="field">
    <h4> <%= form.label :genre_id %> </h4>
    <%= form.collection_select :genre_id, Genre.order(:name), :id, :name, { include_blank: true} %>
  </div>

  <div class="actions">
    <%= form.submit({:class => 'btn btn-success'}) %>
  </div>
<% end %>

app/views/fanfics/edit.html.erb
<h1>Editing Fanfic</h1>

<% if current_user && @fanfic.user_id == current_user.id %>



<%= render 'form', fanfic: @fanfic %>

<span class="btn btn-outline-primary"> <%= link_to 'Show', @fanfic %> </span>
<span class="btn btn-outline-primary"> <%= link_to 'Back', fanfics_path %> </span>
<% end %>

app/views/fanfics/index.html.erb
<p id="notice"><%= notice %></p>

  <tbody>
  <%= render @fanfics %>
  <%= will_paginate @fanfics %>

  </tbody>

app/views/fanfics/new.html.erb
<h1> New fanfic </h1>

<%= render 'form', fanfic: @fanfic %>

<span class="btn btn-outline-primary"> <%= link_to 'Back', fanfics_path %> </span>

app/views/fanfics/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @fanfic.title %></h1>
<p>
  <% if @fanfic.genre.present? %>
    <%= link_to @fanfic.genre.name, @fanfic.genre %>
  <%end %>
</p>
<hr>
<p><%= @fanfic.body.html_safe %></p>
<hr>
<% if user_signed_in? %>
  <%= link_to 'Edit', edit_fanfic_path(@fanfic), class: 'btn btn-warning' %>
  <%= link_to 'Delete', fanfic_path(@fanfic), class: 'btn btn-danger', method: :delete, data: { confirm: 'You sure?' } %>
<% end %>
<%= link_to 'Back', fanfics_path, class: 'btn btn-outline-primary btn-sm' %>
<hr>

<div class="buttons_panel">
<%= link_to 'New chapter', new_fanfic_chapter_path(@fanfic), class: 'btn btn-outline-primary btn-sm' %>
</div>

<%= render partial: 'chapters/index' %>

<h2>Comments</h2>
<% @fanfic.comments.each do |comment| %>
  <div class="alert alert-light">
    <p> <strong> <%= comment.username %> </strong>: <%= comment.body %> </p>
  </div>
<% end %>
<hr>
<% if user_signed_in? %>
  <h2>Create comments</h2>
  <%= form_for([@fanfic, @fanfic.comments.build]) do |f| %>
    <p>
      User<br>
      <%#= @user.username %>
      <%= f.text_field(:username, {:class => 'form-control'}) %>
    </p>
    <p>
      Text comment<br>
      <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>
    <p>
      <%= f.submit("Create comment", {:class => 'btn btn-warning'}) %>
    </p>
  <% end %>
<% end %>

app/views/genres/_form.html.erb
<%= form_with(model: @genre, local: true) do |form| %>
  <% if @genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
        <% genre.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h4> <%= form.label :name %> </h4>
    <%= form.text_field(:name, {:class => 'form-control'}) %>
  </div>

<!--  <div class="field">-->
    <%#= form.label :parent_id %>
    <%#= form.collection_select :parent_id, Genre.where("id != #{genre.id}").order(:name), :id, :name, { include_blank: true} %>
<!--  </div>-->

  <div class="actions">
    <%= form.submit({:class => 'btn btn-success'}) %>
  </div>
<% end %>

app/views/genres/edit.html.erb
<h1>Editing Genre</h1>

<%= render 'form', genre: @genre %>

<span class="btn btn-outline-primary"> <%= link_to 'Show', @genre %> </span>
<span class="btn btn-outline-primary"> <%= link_to 'Back', genres_path %> </span>

app/views/genres/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Genres</h1>

<div class="buttons_panel">
  <%= link_to 'New genre', new_genre_path, class: 'btn btn-outline-primary btn-sm' %>
</div>

<section id="genres">
  <table class="table">
    <thead>
      <tr>
        <th> # </th>
        <th> Name </th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @genres.each_with_index do |genre, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= link_to genre.name, genre %></td>
          <td>
            <%= link_to 'Edit', edit_genre_path(genre), class: 'btn btn-outline-primary btn-sm' %>
            <%= link_to 'Destroy', genre, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/genres/new.html.erb
<h1>New Genre</h1>

<%= render 'form', genre: @genre %>

<span class="btn btn-outline-primary"> <%= link_to 'Back', genres_path %> </span>

app/views/genres/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @genre.name %></h1>
<!--<p>-->
<!--  <strong>Name:</strong>-->
  <%#= @genre.name %>
<!--</p>-->

<section id="fanfics">
  <%= render @fanfics %>
</section>

<%= will_paginate @fanfics, renderer: 'BootstrapPaginationHelper::LinkRenderer' %>

<span class="btn btn-outline-primary"> <%= link_to 'Edit', edit_genre_path(@genre) %> </span>
<span class="btn btn-outline-primary"> <%= link_to 'Back', genre_path %> </span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fanfics</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-bold">Ficbook</h5>
    <nav class="my-2 my-md-0 mr-md-3">
      <span class="p-2 text-dark"> <%= link_to 'Home page', fanfics_path %> </span>
      <span class="p-2 text-dark"> <%= link_to 'Genres', genres_path %> </span>
      <span class="p-2 text-dark"> <%= link_to 'New story', new_fanfic_path %> </span>
      <span class="p-2 text-dark"> <%= link_to 'User page', about_path %> </span>
    </nav>
    <% if user_signed_in? %>
      <span class="btn btn-outline-primary"> <%= link_to 'Sign out', destroy_user_session_path, method: :Delete %> </span>
    <% else %>
      <span class="btn btn-outline-primary"> <%= link_to 'Sign in', new_user_session_path %> </span>
      <span class="btn btn-outline-primary"> <%= link_to 'Sign up', new_user_registration_path %> </span>
    <%end %>
    <span class="nav-item<%= "active" if I18n.locale == :ru %>">
      <%= link_to "Рус", { locale: :ru}, class: "nav-link" %>
    </span>
    <span class="nav-item<%= "active" if I18n.locale == :en %>">
      <%= link_to "En", { locale: :en}, class: "nav-link" %>
    </span>
  </div>



<!--    <p class="notice"><%#= notice %></p>-->
    <p class="alert"><%= alert %></p>

    <div class="row">
      <div class="container"><%= yield %></div>
      <div class="col-md-3">
        <%= render 'shared/submenu' %>
        <h3>Tags</h3>
        <div class="tag_clound">
          <% tag_cloud(Tag.counts, %w{tag1 tag2 tag3 tag4 tag5}) do |tag, css_class| %>
            <%= link_to tag.name, tag_path(tag.name), class: css_class %>
          <% end %>
        </div>
      </div>
    </div>


  </body>


</html>

app/views/pages/about.html.erb
<p id="notice"><%= notice %></p>

<h1>User page</h1>

<section id="fanfics">
  <%= render @user.fanfic_id %>
</section>

<%= will_paginate @fanfics, renderer: 'BootstrapPaginationHelper::LinkRenderer' %>

<!--<section id="fanfics">-->
<!--  <table class="table">-->
<!--    <thead>-->
<!--    <tr>-->
<!--      <th> Title </th>-->
<!--      <th> Body </th>-->
<!--      <th colspan="3"></th>-->
<!--    </tr>-->
<!--    </thead>-->

<!--    <tbody>-->
    <%# @fanfics.each do |fanfic| %>
<!--      <tr>-->
<!--        <td><%#= link_to fanfic.title, fanfic_path(fanfic) %></td>-->
<!--        <td><%#= fanfic.body %></td>-->
<!--        <td>-->
          <%#= link_to 'Edit', edit_fanfic_path(fanfic), class: 'btn btn-outline-primary btn-sm' %>
          <%#= link_to 'Destroy', @fanfic, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger btn-sm' %>
<!--        </td>-->
<!--      </tr>-->
    <%# end %>
<!--    </tbody>-->
<!--  </table>-->
<!--</section>-->

app/views/shared/_submenu.html.erb
<div class="submenu">
  <h2> Genres </h2>
  <ul class="nav nav-pills nav-stacked">
    <% Genre.roots.each do |genre| %>
      <li class="nav-item">
        <%= link_to genre.name, genre, class: "nav-link #{'active' if current_page?(genre_path(genre))}" %>
        <%= render 'shared/submenu_genres', genres: genre.root.descendants.arrange %>
      </li>
    <% end %>
  </ul>
</div>

app/views/shared/_submenu_genres.html.erb
<ul class="nav nav-pills nav-stacked nested_nav">
  <% genres.each do |genre, children| %>
    <li>
      <%= link_to genre.name, genre, class: "nav-link #{'active' if current_page?(genre_path(genre))}" %>
      <%= render 'shared/submenu_genres', genres: children if children.present? %>
    </li>
  <% end %>
</ul>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>

<% if @tag.fanfics.empty? %>
  <h2> Not story</h2>
<% else %>
  <%= render @tag.fanfics %>
<% end %>